test_that("local predicates and listings delegate to fs", {
  path <- tempfile("netfs-local-")
  fs::dir_create(path)
  on.exit(fs::dir_delete(path), add = TRUE)
  file <- fs::path(path, "a.txt")
  writeLines("x", file)
  expect_equal(dir_ls(path), fs::dir_ls(path))
  expect_equal(dir_exists(path), fs::dir_exists(path))
  expect_equal(file_exists(file), fs::file_exists(file))
  expect_equal(file_info(file), fs::file_info(file))
})

test_that("local mutations retain fs behavior", {
  path <- tempfile("netfs-mutate-")
  dir_create(path)
  on.exit(if (fs::dir_exists(path)) fs::dir_delete(path), add = TRUE)
  a <- fs::path(path, "a"); b <- fs::path(path, "b"); c <- fs::path(path, "c")
  writeLines("x", a)
  file_copy(a, b)
  file_move(b, c)
  expect_true(file_exists(c))
  file_delete(c)
  expect_false(file_exists(c))
})
