integration_enabled <- identical(Sys.getenv("NETFS_RUN_INTEGRATION"), "true")

cleanup_remote_file <- function(con, path) {
  try(if (file_exists(path, con)) file_delete(path, con), silent = TRUE)
}

cleanup_remote_dir <- function(con, path) {
  try(if (dir_exists(path, con)) dir_delete(path, con), silent = TRUE)
}

test_that("live SSH backend supports the core workflow", {
  skip_if_not(integration_enabled)
  host <- Sys.getenv("NETFS_TEST_HOST")
  user <- Sys.getenv("NETFS_TEST_USER")
  identity <- Sys.getenv("NETFS_TEST_IDENTITY_FILE")
  root <- paste0("/home/", user, "/netfs-integration")
  con <- ssh(host, user = user, identity_file = identity)
  source <- tempfile(fileext = ".bin")
  payload <- as.raw(c(0L, 1L, 2L, 127L, 255L))
  writeBin(payload, source)
  destination <- tempfile(fileext = ".bin")
  on.exit(unlink(c(source, destination)), add = TRUE)

  if (dir_exists(root, con)) dir_delete(root, con)
  dir_create(root, con)
  on.exit(cleanup_remote_dir(con, root), add = TRUE)
  file_upload(source, root, con)
  remote <- paste0(root, "/", basename(source))
  on.exit(cleanup_remote_file(con, remote), add = TRUE)
  expect_true(file_exists(remote, con))
  expect_true(remote %in% dir_ls(root, con))
  file_download(remote, destination, con)
  expect_identical(readBin(destination, "raw", n = 100L), payload)
  moved <- paste0(root, "/moved.bin")
  file_move(remote, moved, con)
  on.exit(cleanup_remote_file(con, moved), add = TRUE)
  expect_true(file_exists(moved, con))
  file_delete(moved, con)
  dir_delete(root, con)
})

test_that("live FTP backend supports upload, download, move, and delete", {
  skip_if_not(integration_enabled)
  host <- Sys.getenv("NETFS_TEST_HOST")
  user <- Sys.getenv("NETFS_TEST_USER")
  password <- Sys.getenv("NETFS_TEST_PASSWORD")
  con <- ftp(host, user = user, password = password)
  root <- "/netfs-ftp-integration"
  source <- tempfile(fileext = ".txt")
  writeLines("netfs FTP integration", source, useBytes = TRUE)
  destination <- tempfile(fileext = ".txt")
  on.exit(unlink(c(source, destination)), add = TRUE)

  if (dir_exists(root, con)) dir_delete(root, con)
  dir_create(root, con)
  on.exit(cleanup_remote_dir(con, root), add = TRUE)
  file_upload(source, root, con)
  remote <- paste0(root, "/", basename(source))
  on.exit(cleanup_remote_file(con, remote), add = TRUE)
  expect_true(file_exists(remote, con))
  expect_true(remote %in% dir_ls(root, con))
  file_download(remote, destination, con)
  expect_identical(readLines(destination, warn = FALSE), "netfs FTP integration")
  moved <- paste0(root, "/moved.txt")
  file_move(remote, moved, con)
  on.exit(cleanup_remote_file(con, moved), add = TRUE)
  expect_true(file_exists(moved, con))
  file_delete(moved, con)
  dir_delete(root, con)
})

test_that("live SMB backend supports upload, download, move, and delete", {
  skip_if_not(integration_enabled)
  host <- Sys.getenv("NETFS_TEST_HOST")
  share <- Sys.getenv("NETFS_TEST_SMB_SHARE")
  user <- Sys.getenv("NETFS_TEST_USER")
  password <- Sys.getenv("NETFS_TEST_PASSWORD")
  con <- smb(host, share, user = user, password = password)
  root <- "/netfs-smb-integration"
  source <- tempfile(fileext = ".txt")
  writeLines("netfs SMB integration", source, useBytes = TRUE)
  destination <- tempfile(fileext = ".txt")
  on.exit(unlink(c(source, destination)), add = TRUE)

  if (dir_exists(root, con)) dir_delete(root, con)
  dir_create(root, con)
  on.exit(cleanup_remote_dir(con, root), add = TRUE)
  file_upload(source, root, con)
  remote <- paste0(root, "/", basename(source))
  on.exit(cleanup_remote_file(con, remote), add = TRUE)
  expect_true(file_exists(remote, con))
  expect_true(remote %in% dir_ls(root, con))
  file_download(remote, destination, con)
  expect_identical(readLines(destination, warn = FALSE), "netfs SMB integration")
  moved <- paste0(root, "/moved.txt")
  file_move(remote, moved, con)
  on.exit(cleanup_remote_file(con, moved), add = TRUE)
  expect_true(file_exists(moved, con))
  file_delete(moved, con)
  dir_delete(root, con)
})

test_that("live cross-connection transfer copies FTP to SMB", {
  skip_if_not(integration_enabled)
  host <- Sys.getenv("NETFS_TEST_HOST")
  user <- Sys.getenv("NETFS_TEST_USER")
  password <- Sys.getenv("NETFS_TEST_PASSWORD")
  share <- Sys.getenv("NETFS_TEST_SMB_SHARE")
  ftp_con <- ftp(host, user = user, password = password)
  smb_con <- smb(host, share, user = user, password = password)
  ftp_root <- "/netfs-transfer-source"
  smb_root <- "/netfs-transfer-destination"
  source <- tempfile(fileext = ".csv")
  writeLines(c("id,value", "1,test"), source, useBytes = TRUE)
  on.exit(unlink(source), add = TRUE)

  dir_create(ftp_root, ftp_con)
  dir_create(smb_root, smb_con)
  on.exit(cleanup_remote_dir(ftp_con, ftp_root), add = TRUE)
  on.exit(cleanup_remote_dir(smb_con, smb_root), add = TRUE)
  file_upload(source, ftp_root, ftp_con)
  ftp_path <- paste0(ftp_root, "/", basename(source))
  on.exit(cleanup_remote_file(ftp_con, ftp_path), add = TRUE)
  result <- file_transfer(ftp_path, smb_root, ftp_con, smb_con)
  on.exit(cleanup_remote_file(smb_con, result), add = TRUE)
  expect_equal(result, paste0(smb_root, "/", basename(source)))
  expect_true(file_exists(result, smb_con))
  file_delete(ftp_path, ftp_con)
  file_delete(result, smb_con)
  dir_delete(ftp_root, ftp_con)
  dir_delete(smb_root, smb_con)
})
