.dir_ls <- function(con, path, ...) UseMethod(".dir_ls")
.dir_info <- function(con, path, ...) UseMethod(".dir_info")
.dir_info.default <- function(con, path, ...) {
  paths <- .dir_ls(con, path, ...)
  if (!length(paths)) return(.new_remote_info(character()))
  do.call(rbind, lapply(paths, function(p) .file_info(con, p)))
}
.dir_exists <- function(con, path, ...) UseMethod(".dir_exists")
.dir_create <- function(con, path, ...) UseMethod(".dir_create")
.dir_delete <- function(con, path, ...) UseMethod(".dir_delete")
.file_exists <- function(con, path, ...) UseMethod(".file_exists")
.file_delete <- function(con, path, ...) UseMethod(".file_delete")
.file_copy <- function(con, path, new_path, ...) UseMethod(".file_copy")
.file_move <- function(con, path, new_path, ...) UseMethod(".file_move")
.file_info <- function(con, path, ...) UseMethod(".file_info")
.file_download <- function(con, path, local, ...) UseMethod(".file_download")
.file_upload <- function(con, local, path, ...) UseMethod(".file_upload")
